In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import csv
from scipy.stats import linregress

In [2]:
#import Econ data from New Orleans

katrina_1 = "./Economic Data/neworleanshousing.csv"

katrina_Housing_df = pd.read_csv(katrina_1)
katrina_Housing_df.head()

         DATE  ATNHPIUS35380Q
0  1977-04-01           48.77
1  1977-07-01           47.35
2  1977-10-01           53.55
3  1978-01-01           55.29
4  1978-04-01           56.38

In [12]:
# remove rows prior to 2001

katrina_Housing_df['DATE'] = pd.to_datetime(katrina_Housing_df['DATE'])

katrina_Housing_df = katrina_Housing_df[katrina_Housing_df["DATE"] >= '2001-01-01']

#Add hurricane, year, location

katrina_Housing_df[['Hurricane','Hurricane Date','Location']] = pd.DataFrame([['Katrina','2005-08-29','New Orleans Metro Area']], index = katrina_Housing_df.index)

katrina_Housing_df['Hurricane Date'] = pd.to_datetime(katrina_Housing_df['Hurricane Date'])


#We will need to show data from multiple years, so delta from hurricane best option

katrina_Housing_df['Delta'] = ((katrina_Housing_df['DATE'] - katrina_Housing_df['Hurricane Date']).dt.days/365)

if pd.DatetimeIndex(katrina_Housing_df['DATE']).month==1 :
    katrina_Housing_df['Quarter'] = '1'
elif pd.DatetimeIndex(katrina_Housing_df['DATE']).month==4:
    katrina_Housing_df['Quarter'] = '2'
elif  pd.DatetimeIndex(katrina_Housing_df['DATE']).month==7:
    katrina_Housing_df['Quarter'] = '3'    
else:
    katrina_Housing_df['Quarter'] = '4'


katrina_Housing_df['Delta'] = katrina_Housing_df['Delta'].astype(int)

#Rename column 
katrina_Housing_df = katrina_Housing_df.rename(columns={'ATNHPIUS35380Q': 'Housing Price Index'})

katrina_Housing_df.head()

SyntaxError: invalid syntax (Temp/ipykernel_8808/261538644.py, line 18)

In [ ]:
#import Econ data from New Orleans

katrina_2 = "./Economic Data/NOLANewPrivateHousingStructuresAuthorized.csv"

katrina_HousingAuthorized_df = pd.read_csv(katrina_2)
katrina_HousingAuthorized_df.head()

In [ ]:
# remove rows prior to 2001

katrina_HousingAuthorized_df['DATE'] = pd.to_datetime(katrina_HousingAuthorized_df['DATE'])

katrina_HousingAuthorized_df = katrina_HousingAuthorized_df[katrina_HousingAuthorized_df["DATE"] >= '2001-01-01']

#Add hurricane, year, location

katrina_HousingAuthorized_df[['Hurricane','Hurricane Date','Location']] = pd.DataFrame([['Katrina','2005-08-29','New Orleans Metro Area']], index = katrina_HousingAuthorized_df.index)

katrina_HousingAuthorized_df['Hurricane Date'] = pd.to_datetime(katrina_HousingAuthorized_df['Hurricane Date'])


#We will need to show data from multiple years, so delta from hurricane best option
katrina_HousingAuthorized_df['Delta'] = ((katrina_HousingAuthorized_df['DATE'] - katrina_HousingAuthorized_df['Hurricane Date']).dt.days/365)

katrina_HousingAuthorized_df['Delta'] = katrina_HousingAuthorized_df['Delta'].astype(float)

#Rename column 
katrina_HousingAuthorized_df = katrina_HousingAuthorized_df.rename(columns={'NEWO322BPPRIV': 'New Private Housing Structures Authorized'})

katrina_HousingAuthorized_df.head()

In [ ]:
#import Econ data from New Orleans

katrina_3 = "./Economic Data/NOLARealGDP.csv"

katrina_real_GDP_df = pd.read_csv(katrina_3)
katrina_real_GDP_df.head()

In [ ]:
# remove rows prior to 2001

katrina_real_GDP_df['DATE'] = pd.to_datetime(katrina_real_GDP_df['DATE'])

katrina_real_GDP_df = katrina_real_GDP_df[katrina_real_GDP_df["DATE"] >= '2001-01-01']

#Add hurricane, year, location

katrina_real_GDP_df[['Hurricane','Hurricane Date','Location']] = pd.DataFrame([['Katrina','2005-08-29','New Orleans Metro Area']], index = katrina_real_GDP_df.index)

katrina_real_GDP_df['Hurricane Date'] = pd.to_datetime(katrina_real_GDP_df['Hurricane Date'])

katrina_real_GDP_df['Hurricane Year'] = pd.to_datetime(katrina_real_GDP_df['Hurricane Date'],format='%Y%m%d')

katrina_real_GDP_df['Hurricane Year'] = pd.DatetimeIndex(katrina_real_GDP_df['Hurricane Year']).year

katrina_real_GDP_df['Real GDP Year'] = pd.to_datetime(katrina_real_GDP_df['DATE'],format='%Y%m%d')

katrina_real_GDP_df['Real GDP Year'] = pd.DatetimeIndex(katrina_real_GDP_df['Real GDP Year']).year

#We will need to show data from multiple years, so delta from hurricane best option
katrina_real_GDP_df['Delta'] = ((katrina_real_GDP_df['Real GDP Year'] - katrina_real_GDP_df['Hurricane Year']))

katrina_real_GDP_df['Delta'] = katrina_real_GDP_df['Delta'].astype(int)

#Rename column 
katrina_real_GDP_df = katrina_real_GDP_df.rename(columns={'RGMP35380': 'Real GDP'})

katrina_real_GDP_df.head()

In [ ]:
#import Econ data from New Orleans

katrina_4 = "./Economic Data/NOLAUnemployment.csv"

katrina_unemployment_df = pd.read_csv(katrina_4)
katrina_unemployment_df.head()

In [ ]:
# remove rows prior to 2001

katrina_unemployment_df['DATE'] = pd.to_datetime(katrina_unemployment_df['DATE'])

katrina_unemployment_df = katrina_unemployment_df[katrina_unemployment_df["DATE"] >= '2001-01-01']

#Add hurricane, year, location

katrina_unemployment_df[['Hurricane','Hurricane Date','Location']] = pd.DataFrame([['Katrina','2005-08-29','New Orleans Metro Area']], index = katrina_unemployment_df.index)

katrina_unemployment_df['Hurricane Date'] = pd.to_datetime(katrina_unemployment_df['Hurricane Date'])


#We will need to show data from multiple years, so delta from hurricane best option
katrina_unemployment_df['Delta'] = ((katrina_unemployment_df['DATE'] - katrina_unemployment_df['Hurricane Date']).dt.days/365)

katrina_unemployment_df['Delta'] = katrina_unemployment_df['Delta'].astype(float)

#Rename column 
katrina_unemployment_df = katrina_unemployment_df.rename(columns={'NEWO322UR': 'Unemployment'})

katrina_unemployment_df.head()

In [ ]:
#import Econ data from New Orleans

katrina_5 = "./Economic Data/NOLAMedianIncome.csv"

katrina_median_df = pd.read_csv(katrina_5)
katrina_median_df.head()

In [ ]:
# remove rows prior to 2001

katrina_median_df['DATE'] = pd.to_datetime(katrina_median_df['DATE'])

katrina_median_df = katrina_median_df[katrina_median_df["DATE"] >= '2001-01-01']

#Add hurricane, year, location

katrina_median_df[['Hurricane','Hurricane Date','Location']] = pd.DataFrame([['Katrina','2005-08-29','New Orleans Metro Area']], index = katrina_median_df.index)

katrina_median_df['Hurricane Date'] = pd.to_datetime(katrina_median_df['Hurricane Date'])

katrina_median_df['Hurricane Year'] = pd.to_datetime(katrina_median_df['Hurricane Date'],format='%Y%m%d')

katrina_median_df['Hurricane Year'] = pd.DatetimeIndex(katrina_median_df['Hurricane Year']).year

katrina_median_df['Median Income Year'] = pd.to_datetime(katrina_median_df['DATE'],format='%Y%m%d')

katrina_median_df['Median Income Year'] = pd.DatetimeIndex(katrina_median_df['Median Income Year']).year

#We will need to show data from multiple years, so delta from hurricane best option
katrina_median_df['Delta'] = ((katrina_median_df['Median Income Year'] - katrina_median_df['Hurricane Year']))

# katrina_median_df['Delta'] = katrina_median_df['Delta'].astype(int)

katrina_median_df.head()

In [ ]:
#import Econ data from New Orleans

katrina_6 = "./Economic Data/NOLAPopulation.csv"

katrina_population_df = pd.read_csv(katrina_6)
katrina_population_df.head()

In [ ]:
# remove rows prior to 2001

katrina_population_df['DATE'] = pd.to_datetime(katrina_population_df['DATE'])

katrina_population_df = katrina_population_df[katrina_population_df["DATE"] >= '2001-01-01']

#Add hurricane, year, location

katrina_population_df[['Hurricane','Hurricane Date','Location']] = pd.DataFrame([['Katrina','2005-08-29','New Orleans Metro Area']], index = katrina_population_df.index)

katrina_population_df['Hurricane Date'] = pd.to_datetime(katrina_population_df['Hurricane Date'])

katrina_population_df['Hurricane Year'] = pd.to_datetime(katrina_population_df['Hurricane Date'],format='%Y%m%d')

katrina_population_df['Hurricane Year'] = pd.DatetimeIndex(katrina_population_df['Hurricane Year']).year

katrina_population_df['Population Year'] = pd.to_datetime(katrina_population_df['DATE'],format='%Y%m%d')

katrina_population_df['Population Year'] = pd.DatetimeIndex(katrina_population_df['Population Year']).year

#We will need to show data from multiple years, so delta from hurricane best option
katrina_population_df['Delta'] = ((katrina_population_df['Population Year'] - katrina_population_df['Hurricane Year']))

katrina_population_df['Delta'] = katrina_population_df['Delta'].astype(int)

#Rename column 
katrina_population_df = katrina_population_df.rename(columns={'NORPOP': 'Population'})

katrina_population_df.head()

In [ ]:
#export to CSV

output_data_file = './CleanEconData/katrina_cln_unemployment.csv'
  
katrina_unemployment_df.to_csv(output_data_file, sep=',')

output_data_file2 = './CleanEconData/katrina_cln_realGDP.csv'
  
katrina_real_GDP_df.to_csv(output_data_file2, sep=',')

output_data_file3 = './CleanEconData/katrina_cln_housingauth.csv'
  
katrina_HousingAuthorized_df.to_csv(output_data_file3, sep=',')

output_data_file4 = './CleanEconData/katrina_cln_housingpriceindex.csv'
  
katrina_Housing_df.to_csv(output_data_file4, sep=',')

output_data_file5 = './CleanEconData/katrina_cln_median.csv'
  
katrina_median_df.to_csv(output_data_file5, sep=',')

output_data_file6 = './CleanEconData/katrina_cln_population.csv'
  
katrina_population_df.to_csv(output_data_file6, sep=',')